# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  menu:
    main:
      # - name: Tour
      #   url: tour
      #   weight: 10
      - name: News
        url: news
        weight: 20
      - name: People
        url: people
        weight: 30
      - name: Events
        url: event
        weight: 40
      - name: Logs
        url: log
        weight: 50   
      - name: Publications
        url: publication
        weight: 60
      - name: Research
        url: research
        weight: 70
      - name: Contact
        url: contact
        weight: 80

ko:
  languageCode: ko-kr
  contentDir: content/ko
  title: AIML@K # Website name
  menu:
    main:
      # - name: Tour
      #   url: tour
      #   weight: 10
      - name: 새소식
        url: news
        weight: 20
      - name: 사람들
        url: people
        weight: 30
      - name: 이벤트
        url: event
        weight: 40
      - name: 로그
        url: log
        weight: 50   
      - name: 논문
        url: publication
        weight: 60
      - name: 연구
        url: research
        weight: 70
      - name: 연락처
        url: contact
        weight: 800

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
