# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: koreauniversity # minimal
  # theme_night: 
  mode: light
  # color: red # does not work (tailwind) 
# see https://docs.hugoblox.com/getting-started/customize/#color-themes
  font: koreauniversity # native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    # site_type: ResearchOrganization
    local_business_type: ''
    org_name: "Donghun Lee 이동헌 AIMLK"
    description: "Math, AI, and Research by Donghun Lee at Korea University"
    # description: 'Home for those who bridges AI and math, explores the frontiers of them, and sharing the fruits with our society'
    # twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
    pirsch: 'sx4npXpRw5ozuIifDYUnleSMDesvw2g8'
  verification:
    google: 'THRaeCf0FG7uRKsIMjEnA7s-I7Ia_Cs1mh0A0rmtbfw'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: '© {year} Donghun Lee - licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 2

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa

# what would happen if I do this?
i_am_a_sponsor: true

# are there only two power-ups?
power_ups:
  hide_generator: true
  hide_published_with: true